name: soknad-kontantstotte-proxy
image: repo.adeo.no:5443/soknad/soknad-kontantstotte-proxy
team: søknad
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8081
resources:
  limits:
    cpu: 3
healthcheck:
  liveness:
    initialDelay: 60
    path: /api/status/isAlive
  readiness:
    initialDelay: 60
    path: /api/status/isAlive
prometheus:
  enabled: true
  path: /actuator/prometheus
fasitResources:
  used:
  - alias: aad_b2c_clientid
    resourceType: credential
    propertyMap:
      username: NO_NAV_SECURITY_OIDC_ISSUER_SELVBETJENING_ACCEPTEDAUDIENCE
  - alias: aad_b2c_discovery
    resourceType: baseurl
    propertyMap:
      url: NO_NAV_SECURITY_OIDC_ISSUER_SELVBETJENING_DISCOVERYURL
  - alias : securityTokenService
    resourceType: baseurl
  - alias : srvsoknad-kontantstotte-proxy
    resourceType: credential
    propertyMap:
      username: soknadkontantstotte_username
      password: soknadkontantstotte_password
  - alias: virksomhet:Person_v3
    resourceType: webserviceendpoint
  - alias: unleash-api
    resourceType: restservice
  - alias: appres.cms
    resourceType: baseUrl
# DOKMOT STASJ
  - alias: mqGateway01
    resourceType: queuemanager
    propertyMap:
      hostname: DOKMOT_HOSTNAME
      port: DOKMOT_PORT
      name: DOKMOT_NAME
  - alias: dokmot_channel
    resourceType: channel
    propertyMap:
      name: DOKMOT_CHANNELNAME

  - alias: brisdokmot
    resourceType: credential
    propertyMap:
      username: DOKMOT_USERNAME
      password: DOKMOT_PASSWORD

  - alias : dokmot_motta_forsendelse_ditt_nav
    resourceType: queue
    propertyMap:
      queueName: DOKMOT_QUEUENAME
      queueManager: DOKMOT_QUEUEMANAGER
# SLUTT PÅ DOKMOT STASJ
  exposed:
    - alias: soknad-kontantstotte-proxy-api
      resourceType: restservice
      path: /api