name: soknad-kontantstotte-proxy
team: team-soknad
image: repo.adeo.no:5443/soknad/soknad-kontantstotte-proxy
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8081
resources:
  limits:
    cpu: 3
healthcheck:
  liveness:
    initialDelay: 20
    path: /api/status/isAlive
  readiness:
    initialDelay: 20
    path: /api/status/isAlive
prometheus:
  enabled: true
  path: /actuator/prometheus
fasitResources:
  used:
# Appdynamics
  - alias: appdynamics
    resourceType: applicationproperties
# Unleash
  - alias: unleash-api
    resourceType: restservice
# Oidc
  - alias: aad_b2c_clientid
    resourceType: credential
    propertyMap:
      username: NO_NAV_SECURITY_OIDC_ISSUER_SELVBETJENING_ACCEPTEDAUDIENCE
  - alias: aad_b2c_discovery
    resourceType: baseurl
    propertyMap:
      url: NO_NAV_SECURITY_OIDC_ISSUER_SELVBETJENING_DISCOVERYURL
# Dokmot
  - alias: mqGateway01
    resourceType: queuemanager
    propertyMap:
      hostname: DOKMOT_HOSTNAME
      port: DOKMOT_PORT
      name: DOKMOT_NAME
  - alias: dokmot_channel
    resourceType: channel
    propertyMap:
      name: DOKMOT_CHANNELNAME

  - alias: KontantstotteDokmot
    resourceType: credential
    propertyMap:
      username: DOKMOT_USERNAME
      password: DOKMOT_PASSWORD

  - alias : dokmot_MOTTA_FORSENDELSE_DITT_NAV
    resourceType: queue
    propertyMap:
      queueName: DOKMOT_QUEUENAME
      queueManager: DOKMOT_QUEUEMANAGER
# SLUTT PÅ DOKMOT STASJ
  exposed:
    - alias: soknad-kontantstotte-proxy-api
      resourceType: restservice
      path: /api