spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
no.nav.security.oidc:
  issuers: selvbetjening
  issuer.selvbetjening:
     discoveryurl: http://metadata
     accepted_audience: aud-localhost
     cookie_name: localhost-idtoken

UNLEASH_API_URL: http://localhost
APP_NAME: soknad-kontantstotte-proxy

dokmot :
  queuename : ueue
  hostname : hostname
  port : 2412
  name : name
  username : user
  channelname : channel
  enabled: false

logging:
  level:
    org.springframework: WARN
    org.glassfish.jersey: WARN
    org.glassfish.jersey.logging.LoggingFeature: DEBUG
    com.fasterxml: WARN
  config: classpath:logback-spring-test.xml

PERSONINFO_V1_URL: http://localhost

