spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
no.nav.security.oidc:
  issuers: selvbetjening
  issuer.selvbetjening:
     discoveryurl: http://metadata
     accepted_audience: aud-localhost
     cookie_name: localhost-idtoken

SECURITYTOKENSERVICE_URL: http://localhost
SOKNADKONTANTSTOTTE_USERNAME: something
SOKNADKONTANTSTOTTE_PASSWORD: bogus
VIRKSOMHET_PERSON_V3_ENDPOINTURL: http://localhost
UNLEASH_API_URL: http://localhost
APP_NAME: soknad-kontantstotte-proxy